### ISSUE TITLE
qwen-image train failed

### ISSUE THREAD

**Issue by meitianwang** [tdrussell/diffusion-pipe#365]
I have successfully trained wan2.1 and kontext using this project in my environment, but failed to train qwen image. I tried upgrading the versions of Torch and TorchVision but still got the same error. The error log is:

Traceback (most recent call last):
[23:37:27][rank0]:   File "/root/diffusion-pipe/train.py", line 333, in <module>
[23:37:27][rank0]:     from models import qwen_image
[23:37:27][rank0]:   File "/root/diffusion-pipe/models/qwen_image.py", line 9, in <module>
[23:37:27][rank0]:     from diffusers.models.attention_dispatch import dispatch_attention_fn
[23:37:27][rank0]: ModuleNotFoundError: No module named 'diffusers.models.attention_dispatch'

My torch version is 2.6.0, torch vision is 0.21.0, and Python version is 3.10

**Comment by kabachuha** [comment]
Did you update your diffusers library?

**Comment by meitianwang** [comment]
yes,with commands:
+pip uninstall diffusers
+pip install git+https://github.com/huggingface/diffusers

**Comment by tdrussell** [comment]
That error is the exact error I get if I use the latest stable Diffusers instead of from source. Are you sure you are setting up the environment and dependencies correctly?

The only other thing I notice is Python 3.10. I use Python 3.12 and the install instructions specify that version as well.

**Comment by meitianwang** [comment]
> 如果我使用最新的稳定版 Diffusers 而不是源代码，就会出现这个错误。你确定你正确设置了环境和依赖项吗？
> 
> 我唯一注意到的另一件事是 Python 3.10。我使用的是 Python 3.12，安装说明也指定了该版本。
Following your instructions, I reinstalled all dependencies, upgraded Python to 3.12, and also upgraded to the latest diffusers. Now qwen-image can be trained successfully! ! However, flux_kontext fails with the following error:

[2025-08-08 07:58:42,977] [INFO] [engine.py:165:__init__] RANK=0 STAGE=0 LAYERS=60 [0, 60) STAGE_PARAMS=171835392 (171.835M) TOTAL_PARAMS=171835392 (171.835M) UNIQUE_PARAMS=171835392 (171.835M)
[rank0]: Traceback (most recent call last):
[rank0]:   File "/root/diffusion-pipe/train.py", line 756, in <module>
[rank0]:     loss = model_engine.train_batch(iterator).item()
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/pipe/engine.py", line 389, in train_batch
[rank0]:     self._exec_schedule(sched)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/pipe/engine.py", line 1423, in _exec_schedule
[rank0]:     self._exec_instr(**cmd.kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/pipe/engine.py", line 736, in _exec_forward_pass
[rank0]:     outputs = super().forward(inputs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/utils/nvtx.py", line 20, in wrapped_fn
[rank0]:     ret_val = func(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/engine.py", line 2063, in forward
[rank0]:     loss = self.module(*inputs, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1845, in _call_impl
[rank0]:     return inner()
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1793, in inner
[rank0]:     result = forward_call(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/pipe/module.py", line 388, in forward
[rank0]:     x = self.activation_checkpoint_func(exec_range_func(start_idx, end_idx), *x)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/_compile.py", line 32, in inner
[rank0]:     return disable_fn(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/_dynamo/eval_frame.py", line 745, in _fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/root/diffusion-pipe/utils/unsloth_utils.py", line 71, in unsloth_checkpoint
[rank0]:     return Unsloth_Offloaded_Gradient_Checkpointer.apply(function, *args)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 575, in apply
[rank0]:     return super().apply(*args, **kwargs)  # type: ignore[misc]
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/amp/autocast_mode.py", line 503, in decorate_fwd
[rank0]:     return fwd(*args, **kwargs)
[rank0]:   File "/root/diffusion-pipe/utils/unsloth_utils.py", line 35, in forward
[rank0]:     output = forward_function(hidden_states, *args)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/deepspeed/runtime/pipe/module.py", line 365, in exec_func
[rank0]:     inputs = layer(inputs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/amp/autocast_mode.py", line 44, in decorate_autocast
[rank0]:     return func(*args, **kwargs)
[rank0]:   File "/root/diffusion-pipe/models/flux.py", line 530, in forward
[rank0]:     hidden_states = self.block(
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:   File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1750, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]: TypeError: FluxSingleTransformerBlock.forward() missing 1 required positional argument: 'encoder_hidden_states'

**Comment by meitianwang** [comment]
Is it because of upgrading the latest diffusers?

**Comment by tdrussell** [comment]
Yes, Diffusers made a breaking change to one of the Flux transformer blocks. The latest change should fix it.

**Comment by meitianwang** [comment]
> 是的，扩散器对其中一个 Flux 变压器模块进行了重大更改。最新的更改应该可以修复这个问题。

那应该怎么同时支持qwen-image和flux-kontext的训练呢

**Comment by samliu315** [comment]
@tdrussell  I've checked all the parameters and configurations and didn't find anything unusual. But I'm still getting this error. Any ideas?

[2025-08-09 23:24:29,019] [ERROR] [launch.py:325:sigkill_handler] ['/root/miniconda3/bin/python', '-u', 'train.py', '--local_rank=0', '--deepspeed', '--config', 'examples/qwen_image_24gb_vram.toml'] exits with return code = -11

**Comment by tdrussell** [comment]
@samliu315 If the OS is killing the process out of nowhere, with no error message or stack trace, you are probably running out of RAM. Qwen-Image is a large model, you probably need at least 64GB RAM especially if you are doing significant block swapping.
